import type { ToolEntry } from "./types";

// Converter tool entries
export const CONVERT_TOOLS: ToolEntry[] = [
  // Video
  { label: "Video Converter", desc: "Any video format", cat: "video", icon: "VID", type: "video" },
  { label: "MP4 Converter", desc: "Convert to MP4", cat: "video", icon: "MP4", type: "video", format: "mp4" },
  { label: "MKV Converter", desc: "Convert to MKV", cat: "video", icon: "MKV", type: "video", format: "mkv" },
  { label: "AVI Converter", desc: "Convert to AVI", cat: "video", icon: "AVI", type: "video", format: "avi" },
  { label: "MOV Converter", desc: "Convert to MOV", cat: "video", icon: "MOV", type: "video", format: "mov" },
  { label: "WEBM Converter", desc: "Convert to WebM", cat: "video", icon: "WBM", type: "video", format: "webm" },
  { label: "FLV Converter", desc: "Convert to FLV", cat: "video", icon: "FLV", type: "video", format: "flv" },
  { label: "WMV Converter", desc: "Convert to WMV", cat: "video", icon: "WMV", type: "video", format: "wmv" },
  { label: "MOV to MP4", desc: "Apple to MP4", cat: "video", icon: "MOV", type: "video", format: "mp4" },
  { label: "AVI to MP4", desc: "AVI to MP4", cat: "video", icon: "AVI", type: "video", format: "mp4" },
  { label: "WEBM to MP4", desc: "WebM to MP4", cat: "video", icon: "WBM", type: "video", format: "mp4" },
  { label: "MKV to MP4", desc: "Matroska to MP4", cat: "video", icon: "MP4", type: "video", format: "mp4" },
  { label: "FLV to MP4", desc: "Flash to MP4", cat: "video", icon: "MP4", type: "video", format: "mp4" },
  { label: "WMV to MP4", desc: "WMV to MP4", cat: "video", icon: "WMV", type: "video", format: "mp4" },
  { label: "MP4 to MOV", desc: "MP4 to Apple MOV", cat: "video", icon: "MOV", type: "video", format: "mov" },
  { label: "MP4 to WEBM", desc: "MP4 to WebM", cat: "video", icon: "WEBM", type: "video", format: "webm" },
  { label: "MP4 to AVI", desc: "MP4 to AVI", cat: "video", icon: "AVI", type: "video", format: "avi" },
  { label: "MP4 to MKV", desc: "MP4 to Matroska", cat: "video", icon: "MKV", type: "video", format: "mkv" },
  { label: "TS Converter", desc: "Convert to MPEG-TS", cat: "video", icon: "TS", type: "video", format: "ts" },
  { label: "3GP Converter", desc: "Convert to 3GP", cat: "video", icon: "3GP", type: "video", format: "3gp" },
  { label: "OGV Converter", desc: "Convert to OGV", cat: "video", icon: "OGV", type: "video", format: "ogv" },
  { label: "M4V Converter", desc: "Convert to M4V", cat: "video", icon: "M4V", type: "video", format: "m4v" },

  // Audio
  { label: "Audio Converter", desc: "Any audio format", cat: "audio", icon: "AUD", type: "audio" },
  { label: "MP3 Converter", desc: "Convert to MP3", cat: "audio", icon: "MP3", type: "audio", format: "mp3" },
  { label: "WAV Converter", desc: "Convert to WAV", cat: "audio", icon: "WAV", type: "audio", format: "wav" },
  { label: "OGG Converter", desc: "Convert to OGG", cat: "audio", icon: "OGG", type: "audio", format: "ogg" },
  { label: "FLAC Converter", desc: "Convert to FLAC", cat: "audio", icon: "FLC", type: "audio", format: "flac" },
  { label: "AAC Converter", desc: "Convert to AAC", cat: "audio", icon: "AAC", type: "audio", format: "aac" },
  { label: "M4A Converter", desc: "Convert to M4A", cat: "audio", icon: "M4A", type: "audio", format: "m4a" },
  { label: "WMA Converter", desc: "Convert to WMA", cat: "audio", icon: "WMA", type: "audio", format: "wma" },
  { label: "OPUS Converter", desc: "Convert to Opus", cat: "audio", icon: "OPS", type: "audio", format: "opus" },
  { label: "AIFF Converter", desc: "Convert to AIFF", cat: "audio", icon: "AIF", type: "audio", format: "aiff" },
  { label: "MP4 to MP3", desc: "Extract audio", cat: "audio", icon: "VID", type: "video", format: "mp3" },
  { label: "Video to MP3", desc: "Extract audio", cat: "audio", icon: "VID", type: "video", format: "mp3" },
  { label: "Video to WAV", desc: "Extract lossless", cat: "audio", icon: "VID", type: "video", format: "wav" },
  { label: "WAV to MP3", desc: "WAV to MP3", cat: "audio", icon: "WAV", type: "audio", format: "mp3" },
  { label: "MP3 to WAV", desc: "MP3 to WAV", cat: "audio", icon: "MP3", type: "audio", format: "wav" },
  { label: "MP3 to OGG", desc: "MP3 to OGG", cat: "audio", icon: "MP3", type: "audio", format: "ogg" },
  { label: "MP3 to AAC", desc: "MP3 to AAC", cat: "audio", icon: "MP3", type: "audio", format: "aac" },
  { label: "MP3 to FLAC", desc: "MP3 to Lossless", cat: "audio", icon: "MP3", type: "audio", format: "flac" },
  { label: "MP3 to M4A", desc: "MP3 to M4A", cat: "audio", icon: "MP3", type: "audio", format: "m4a" },
  { label: "FLAC to MP3", desc: "Lossless to MP3", cat: "audio", icon: "FLC", type: "audio", format: "mp3" },
  { label: "FLAC to WAV", desc: "FLAC to WAV", cat: "audio", icon: "FLC", type: "audio", format: "wav" },
  { label: "FLAC to AAC", desc: "FLAC to AAC", cat: "audio", icon: "FLC", type: "audio", format: "aac" },
  { label: "FLAC to M4A", desc: "FLAC to M4A", cat: "audio", icon: "FLC", type: "audio", format: "m4a" },
  { label: "FLAC to OGG", desc: "FLAC to OGG", cat: "audio", icon: "FLC", type: "audio", format: "ogg" },
  { label: "FLAC to OPUS", desc: "FLAC to Opus", cat: "audio", icon: "FLC", type: "audio", format: "opus" },
  { label: "OGG to MP3", desc: "OGG to MP3", cat: "audio", icon: "OGG", type: "audio", format: "mp3" },
  { label: "OGG to WAV", desc: "OGG to WAV", cat: "audio", icon: "OGG", type: "audio", format: "wav" },
  { label: "OGG to FLAC", desc: "OGG to lossless", cat: "audio", icon: "OGG", type: "audio", format: "flac" },
  { label: "OGG to M4A", desc: "OGG to M4A", cat: "audio", icon: "OGG", type: "audio", format: "m4a" },
  { label: "AAC to MP3", desc: "AAC to MP3", cat: "audio", icon: "AAC", type: "audio", format: "mp3" },
  { label: "AAC to WAV", desc: "AAC to WAV", cat: "audio", icon: "AAC", type: "audio", format: "wav" },
  { label: "AAC to FLAC", desc: "AAC to lossless", cat: "audio", icon: "AAC", type: "audio", format: "flac" },
  { label: "AAC to M4A", desc: "AAC to M4A", cat: "audio", icon: "AAC", type: "audio", format: "m4a" },
  { label: "AAC to OGG", desc: "AAC to OGG", cat: "audio", icon: "AAC", type: "audio", format: "ogg" },
  { label: "M4A to MP3", desc: "M4A to MP3", cat: "audio", icon: "M4A", type: "audio", format: "mp3" },
  { label: "M4A to WAV", desc: "M4A to WAV", cat: "audio", icon: "M4A", type: "audio", format: "wav" },
  { label: "M4A to FLAC", desc: "M4A to lossless", cat: "audio", icon: "M4A", type: "audio", format: "flac" },
  { label: "M4A to AAC", desc: "M4A to AAC", cat: "audio", icon: "M4A", type: "audio", format: "aac" },
  { label: "M4A to OGG", desc: "M4A to OGG", cat: "audio", icon: "M4A", type: "audio", format: "ogg" },
  { label: "WMA to MP3", desc: "WMA to MP3", cat: "audio", icon: "WMA", type: "audio", format: "mp3" },
  { label: "WAV to FLAC", desc: "WAV to lossless", cat: "audio", icon: "WAV", type: "audio", format: "flac" },
  { label: "WAV to AAC", desc: "WAV to AAC", cat: "audio", icon: "WAV", type: "audio", format: "aac" },
  { label: "WAV to M4A", desc: "WAV to M4A", cat: "audio", icon: "WAV", type: "audio", format: "m4a" },
  { label: "WAV to OPUS", desc: "WAV to Opus", cat: "audio", icon: "WAV", type: "audio", format: "opus" },

  // Audio extraction from video
  { label: "Video to M4A", desc: "Extract M4A audio", cat: "audio", icon: "M4A", type: "video", format: "m4a" },
  { label: "Video to AAC", desc: "Extract AAC audio", cat: "audio", icon: "AAC", type: "video", format: "aac" },
  { label: "Video to FLAC", desc: "Extract lossless FLAC", cat: "audio", icon: "FLC", type: "video", format: "flac" },
  { label: "Video to OGG", desc: "Extract OGG audio", cat: "audio", icon: "OGG", type: "video", format: "ogg" },
  { label: "Video to OPUS", desc: "Extract Opus audio", cat: "audio", icon: "OPS", type: "video", format: "opus" },
  { label: "Video to WMA", desc: "Extract WMA audio", cat: "audio", icon: "WMA", type: "video", format: "wma" },
  { label: "Video to AIFF", desc: "Extract AIFF audio", cat: "audio", icon: "AIF", type: "video", format: "aiff" },
  { label: "MP4 to M4A", desc: "MP4 to M4A audio", cat: "audio", icon: "M4A", type: "video", format: "m4a" },
  { label: "MP4 to AAC", desc: "MP4 to AAC audio", cat: "audio", icon: "AAC", type: "video", format: "aac" },
  { label: "MP4 to FLAC", desc: "MP4 to lossless", cat: "audio", icon: "FLC", type: "video", format: "flac" },
  { label: "MP4 to OGG", desc: "MP4 to OGG audio", cat: "audio", icon: "OGG", type: "video", format: "ogg" },
  { label: "MKV to MP3", desc: "MKV to MP3 audio", cat: "audio", icon: "MP3", type: "video", format: "mp3" },
  { label: "MKV to M4A", desc: "MKV to M4A audio", cat: "audio", icon: "M4A", type: "video", format: "m4a" },
  { label: "MKV to FLAC", desc: "MKV to lossless", cat: "audio", icon: "FLC", type: "video", format: "flac" },
  { label: "AVI to MP3", desc: "AVI to MP3 audio", cat: "audio", icon: "MP3", type: "video", format: "mp3" },
  { label: "MOV to MP3", desc: "MOV to MP3 audio", cat: "audio", icon: "MP3", type: "video", format: "mp3" },
  { label: "MOV to M4A", desc: "MOV to M4A audio", cat: "audio", icon: "M4A", type: "video", format: "m4a" },
  { label: "WEBM to MP3", desc: "WebM to MP3 audio", cat: "audio", icon: "MP3", type: "video", format: "mp3" },
  { label: "WEBM to OGG", desc: "WebM to OGG audio", cat: "audio", icon: "OGG", type: "video", format: "ogg" },
  { label: "FLV to MP3", desc: "FLV to MP3 audio", cat: "audio", icon: "MP3", type: "video", format: "mp3" },

  // Image
  { label: "Image Converter", desc: "Any image format", cat: "image", icon: "IMG", type: "image" },
  { label: "JPG Converter", desc: "Convert to JPEG", cat: "image", icon: "JPG", type: "image", format: "jpg" },
  { label: "PNG Converter", desc: "Convert to PNG", cat: "image", icon: "PNG", type: "image", format: "png" },
  { label: "WEBP Converter", desc: "Convert to WebP", cat: "image", icon: "WBP", type: "image", format: "webp" },
  { label: "AVIF Converter", desc: "Convert to AVIF", cat: "image", icon: "AVF", type: "image", format: "avif" },
  { label: "BMP Converter", desc: "Convert to BMP", cat: "image", icon: "BMP", type: "image", format: "bmp" },
  { label: "TIFF Converter", desc: "Convert to TIFF", cat: "image", icon: "TIF", type: "image", format: "tiff" },
  { label: "ICO Converter", desc: "Convert to ICO", cat: "image", icon: "ICO", type: "image", format: "ico" },
  { label: "JXL Converter", desc: "Convert to JPEG XL", cat: "image", icon: "JXL", type: "image", format: "jxl" },
  { label: "HEIF Converter", desc: "Convert to HEIF", cat: "image", icon: "HIF", type: "image", format: "heif" },
  { label: "WEBP to PNG", desc: "WebP to PNG", cat: "image", icon: "WBP", type: "image", format: "png" },
  { label: "WEBP to JPG", desc: "WebP to JPEG", cat: "image", icon: "WBP", type: "image", format: "jpg" },
  { label: "WEBP to AVIF", desc: "WebP to AVIF", cat: "image", icon: "WBP", type: "image", format: "avif" },
  { label: "PNG to JPG", desc: "PNG to JPEG", cat: "image", icon: "PNG", type: "image", format: "jpg" },
  { label: "PNG to WEBP", desc: "PNG to WebP", cat: "image", icon: "PNG", type: "image", format: "webp" },
  { label: "PNG to AVIF", desc: "PNG to AVIF", cat: "image", icon: "PNG", type: "image", format: "avif" },
  { label: "PNG to BMP", desc: "PNG to Bitmap", cat: "image", icon: "PNG", type: "image", format: "bmp" },
  { label: "JPG to PNG", desc: "JPEG to PNG", cat: "image", icon: "JPG", type: "image", format: "png" },
  { label: "JPG to WEBP", desc: "JPEG to WebP", cat: "image", icon: "JPG", type: "image", format: "webp" },
  { label: "JPG to AVIF", desc: "JPEG to AVIF", cat: "image", icon: "JPG", type: "image", format: "avif" },
  { label: "JPG to BMP", desc: "JPEG to Bitmap", cat: "image", icon: "JPG", type: "image", format: "bmp" },
  { label: "JPG to TIFF", desc: "JPEG to TIFF", cat: "image", icon: "JPG", type: "image", format: "tiff" },
  { label: "AVIF to JPG", desc: "AVIF to JPEG", cat: "image", icon: "AVF", type: "image", format: "jpg" },
  { label: "AVIF to PNG", desc: "AVIF to PNG", cat: "image", icon: "AVF", type: "image", format: "png" },
  { label: "AVIF to WEBP", desc: "AVIF to WebP", cat: "image", icon: "AVF", type: "image", format: "webp" },
  { label: "HEIC to JPG", desc: "Apple HEIC to JPEG", cat: "image", icon: "HIC", type: "image", format: "jpg" },
  { label: "HEIC to PNG", desc: "Apple HEIC to PNG", cat: "image", icon: "HIC", type: "image", format: "png" },
  { label: "HEIC to WEBP", desc: "Apple HEIC to WebP", cat: "image", icon: "HIC", type: "image", format: "webp" },
  { label: "BMP to PNG", desc: "Bitmap to PNG", cat: "image", icon: "BMP", type: "image", format: "png" },
  { label: "BMP to JPG", desc: "Bitmap to JPEG", cat: "image", icon: "BMP", type: "image", format: "jpg" },
  { label: "TIFF to JPG", desc: "TIFF to JPEG", cat: "image", icon: "TIF", type: "image", format: "jpg" },
  { label: "TIFF to PNG", desc: "TIFF to PNG", cat: "image", icon: "TIF", type: "image", format: "png" },
  { label: "SVG to PNG", desc: "SVG to PNG", cat: "image", icon: "SVG", type: "image", format: "png" },
  { label: "SVG to JPG", desc: "SVG to JPEG", cat: "image", icon: "SVG", type: "image", format: "jpg" },
  { label: "SVG to WEBP", desc: "SVG to WebP", cat: "image", icon: "SVG", type: "image", format: "webp" },
  { label: "GIF to PNG", desc: "GIF to PNG", cat: "image", icon: "GIF", type: "image", format: "png" },
  { label: "GIF to JPG", desc: "GIF to JPEG", cat: "image", icon: "GIF", type: "image", format: "jpg" },
  { label: "GIF to WEBP", desc: "GIF to WebP", cat: "image", icon: "GIF", type: "image", format: "webp" },
  { label: "GIF to AVIF", desc: "GIF to AVIF", cat: "image", icon: "GIF", type: "image", format: "avif" },

  // PDF
  { label: "PDF to PNG", desc: "PDF pages to PNG", cat: "pdf", icon: "PDF", type: "pdf", format: "png" },
  { label: "PDF to JPG", desc: "PDF pages to JPEG", cat: "pdf", icon: "PDF", type: "pdf", format: "jpg" },
  { label: "PDF to WEBP", desc: "PDF pages to WebP", cat: "pdf", icon: "PDF", type: "pdf", format: "webp" },
  { label: "PDF to AVIF", desc: "PDF pages to AVIF", cat: "pdf", icon: "PDF", type: "pdf", format: "avif" },
  { label: "PDF to TIFF", desc: "PDF pages to TIFF", cat: "pdf", icon: "PDF", type: "pdf", format: "tiff" },
  { label: "PDF to BMP", desc: "PDF pages to BMP", cat: "pdf", icon: "PDF", type: "pdf", format: "bmp" },
  { label: "PDF to GIF", desc: "PDF pages to GIF", cat: "pdf", icon: "PDF", type: "pdf", format: "gif" },
  { label: "Image to PDF", desc: "Any image to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "JPG to PDF", desc: "JPEG to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "PNG to PDF", desc: "PNG to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "WEBP to PDF", desc: "WebP to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "AVIF to PDF", desc: "AVIF to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "BMP to PDF", desc: "Bitmap to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },
  { label: "TIFF to PDF", desc: "TIFF to PDF", cat: "pdf", icon: "PDF", type: "image", format: "pdf" },

  // GIF
  { label: "Video to GIF", desc: "Create animated GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "MP4 to GIF", desc: "MP4 to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "WEBM to GIF", desc: "WebM to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "MOV to GIF", desc: "MOV to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "AVI to GIF", desc: "AVI to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "MKV to GIF", desc: "MKV to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "FLV to GIF", desc: "FLV to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "WMV to GIF", desc: "WMV to GIF", cat: "gif", icon: "GIF", type: "video", format: "gif" },
  { label: "GIF to MP4", desc: "GIF to video", cat: "gif", icon: "MP4", type: "image", format: "mp4" },
  { label: "GIF to WEBM", desc: "GIF to WebM", cat: "gif", icon: "WBM", type: "image", format: "webm" },
];

// Compressor tool entries
export const COMPRESS_TOOLS: ToolEntry[] = [
  { label: "Video Compressor", desc: "Reduce any video size", cat: "video", icon: "VID", type: "video" },
  { label: "MP4 Compressor", desc: "Shrink MP4 files", cat: "video", icon: "MP4", type: "video", format: "mp4" },
  { label: "MKV Compressor", desc: "Shrink MKV files", cat: "video", icon: "MKV", type: "video", format: "mkv" },
  { label: "MOV Compressor", desc: "Shrink MOV files", cat: "video", icon: "MOV", type: "video", format: "mov" },
  { label: "WEBM Compressor", desc: "Shrink WebM files", cat: "video", icon: "WBM", type: "video", format: "webm" },
  { label: "AVI Compressor", desc: "Shrink AVI files", cat: "video", icon: "AVI", type: "video", format: "avi" },
  { label: "Audio Compressor", desc: "Reduce any audio size", cat: "audio", icon: "AUD", type: "audio" },
  { label: "MP3 Compressor", desc: "Shrink MP3 files", cat: "audio", icon: "MP3", type: "audio", format: "mp3" },
  { label: "WAV Compressor", desc: "Shrink WAV files", cat: "audio", icon: "WAV", type: "audio", format: "wav" },
  { label: "FLAC Compressor", desc: "Shrink FLAC files", cat: "audio", icon: "FLC", type: "audio", format: "flac" },
  { label: "OGG Compressor", desc: "Shrink OGG files", cat: "audio", icon: "OGG", type: "audio", format: "ogg" },
  { label: "AAC Compressor", desc: "Shrink AAC files", cat: "audio", icon: "AAC", type: "audio", format: "aac" },
  { label: "M4A Compressor", desc: "Shrink M4A files", cat: "audio", icon: "M4A", type: "audio", format: "m4a" },
  { label: "Image Compressor", desc: "Reduce any image size", cat: "image", icon: "IMG", type: "image" },
  { label: "JPEG Compressor", desc: "Shrink JPEG files", cat: "image", icon: "JPG", type: "image", format: "jpg" },
  { label: "PNG Compressor", desc: "Shrink PNG files", cat: "image", icon: "PNG", type: "image", format: "png" },
  { label: "WEBP Compressor", desc: "Shrink WebP files", cat: "image", icon: "WBP", type: "image", format: "webp" },
  { label: "AVIF Compressor", desc: "Shrink AVIF files", cat: "image", icon: "AVF", type: "image", format: "avif" },
  { label: "TIFF Compressor", desc: "Shrink TIFF files", cat: "image", icon: "TIF", type: "image", format: "tiff" },
  { label: "GIF Compressor", desc: "Reduce GIF size", cat: "gif", icon: "GIF", type: "image", format: "gif" },
];
